package cl.bicevida.apv.model.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-08-30T18:13:34.768-03:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "WSApvEJBWebServiceService", 
                  wsdlLocation = "http://canis.bicevida.cl:7777/WSApvJAR/WSApvEJB?WSDL",
                  targetNamespace = "http://services.model.apv.bicevida.cl/") 
public class WSApvEJBWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services.model.apv.bicevida.cl/", "WSApvEJBWebServiceService");
    public final static QName WSApvEJB = new QName("http://services.model.apv.bicevida.cl/", "WSApvEJB");
    static {
        URL url = null;
        try {
            url = new URL("http://canis.bicevida.cl:7777/WSApvJAR/WSApvEJB?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSApvEJBWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://canis.bicevida.cl:7777/WSApvJAR/WSApvEJB?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public WSApvEJBWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSApvEJBWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSApvEJBWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WSApvEJBWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSApvEJBWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSApvEJBWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WSApvEJBWebService
     */
    @WebEndpoint(name = "WSApvEJB")
    public WSApvEJBWebService getWSApvEJB() {
        return super.getPort(WSApvEJB, WSApvEJBWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSApvEJBWebService
     */
    @WebEndpoint(name = "WSApvEJB")
    public WSApvEJBWebService getWSApvEJB(WebServiceFeature... features) {
        return super.getPort(WSApvEJB, WSApvEJBWebService.class, features);
    }

}
