package cl.bicevida.apv.model.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-08-30T18:13:34.766-03:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://services.model.apv.bicevida.cl/", name = "WSApvEJBWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface WSApvEJBWebService {

    @WebMethod
    @RequestWrapper(localName = "getProductosAPV", targetNamespace = "http://services.model.apv.bicevida.cl/", className = "cl.bicevida.apv.model.services.GetProductosAPV")
    @ResponseWrapper(localName = "getProductosAPVResponse", targetNamespace = "http://services.model.apv.bicevida.cl/", className = "cl.bicevida.apv.model.services.GetProductosAPVResponse")
    @WebResult(name = "return", targetNamespace = "http://services.model.apv.bicevida.cl/")
    public cl.bicevida.apv.model.services.ListOfProducto getProductosAPV(
        @WebParam(name = "InProducto_1", targetNamespace = "http://services.model.apv.bicevida.cl/")
        cl.bicevida.apv.model.services.InProducto inProducto1
    );
}
